services: 
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ".:/usr/src/app"

  db:
    image: jitesoft/sqlite:latest
    volumes:
      - "./data:/data"
